{
 "title": "GRPC",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "NS",
    "query": {
     "query": "label_values(runtime_uptime{}, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values({__name__=~\"grpc_server_handled_total|grpc_client_handled_total\", namespace=\"$NS\"}, service)"
    }
   },
   {
    "name": "stage",
    "query": {
     "query": "label_values(runtime_uptime{namespace=\"$NS\"}, deployment_environment)"
    }
   },
   {
    "name": "le",
    "query": "\"0.005\",\"0.01\",\"0.025\",\"0.05\",\"0.1\",\"0.25\",\"0.5\",\"1\",\"2.5\",\"5\",\"10\",\"+Inf\""
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min_over_time(runtime_uptime{namespace=\"$NS\", deployment_environment=\"$stage\", service=\"$service\"}[15s]) /1000"
    }
   ]
  },
  {
   "title": "Global Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handled_total{service=\"$service\", namespace=\"$NS\", grpc_type=\"unary\", grpc_code=\"OK\"}[$__interval])) OR on() vector(0) + \nsum(rate(grpc_server_handled_total{service=\"$service\", namespace=\"$NS\", grpc_type=\"unary\", grpc_code=\"NotFound\"}[$__interval])) OR on() vector(0) + \nsum(rate(grpc_server_handled_total{service=\"$service\", namespace=\"$NS\", grpc_type=\"unary\", grpc_code=\"PermissionDenied\"}[$__interval])) OR on() vector(0) + \nsum(rate(grpc_server_handled_total{service=\"$service\", namespace=\"$NS\", grpc_type=\"unary\", grpc_code=\"InvalidArgument\"}[$__interval])) OR on() vector(0))\n/ \nsum(rate(grpc_server_handled_total{service=\"$service\", namespace=\"$NS\", grpc_type=\"unary\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(grpc_server_started_total{service=\"$service\", namespace=\"$NS\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time{namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"}[ $__interval])) by(state,service_instance_id)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_runtime_go_goroutines{namespace=\"$NS\", deployment_environment=\"$stage\", service=\"$service\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(process_runtime_go_gc_pause_total_ns{namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"}[$__interval])",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_heap_sys{namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"}) by (service_instance_id)",
     "legendFormat": "virtual address space {{service_instance_id}}"
    },
    {
     "expr": "sum(process_runtime_go_mem_heap_alloc{namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"}) by (service_instance_id)",
     "legendFormat": "allocated heap object  {{service_instance_id}} "
    },
    {
     "expr": "sum(process_runtime_go_mem_heap_inuse{namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"}) by (service_instance_id)",
     "legendFormat": "in-use spans {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_alloc{service=\"$service\", namespace=\"$NS\"}",
     "legendFormat": "bytes allocated | {{service_instance_id}}"
    },
    {
     "expr": "process_runtime_go_mem_heap_inuse{service=\"$service\", namespace=\"$NS\"}",
     "legendFormat": "heap inuse | {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "system_memory_usage{namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"} / 1024 / 1024",
     "legendFormat": "{{state}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "gRPC server requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "grpc_service",
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC request code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{service=\"$service\", namespace=\"$NS\", grpc_type=\"unary\"}[$__interval])) by (grpc_code)",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(grpc_server_started_total{service=\"$service\", namespace=\"$NS\"}[$__interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Average handling time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(rate(grpc_server_handling_seconds_sum{service=\"$service\", namespace=\"$NS\",grpc_type=\"unary\"}[$__interval])) by (grpc_method) * 1000",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request error rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{service=\"$service\", namespace=\"$NS\", grpc_code!=\"OK\"}[$__interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request error percentage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{service=\"$service\", namespace=\"$NS\", grpc_code!=\"OK\"}[$__interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{service=\"$service\", namespace=\"$NS\"}[$__interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99%-tile latency of requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{service=\"$service\", namespace=\"$NS\"}[$__interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Percentage of slow queries",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{service=\"$service\", namespace=\"$NS\",le=\"$le\"}[$__interval])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_count{service=\"$service\", namespace=\"$NS\"}[$__interval])) by (grpc_method)\n) * 100.0",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC client requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_client_msg_sent_total{service=\"$service\", namespace=\"$NS\", grpc_type=\"unary\"}[$__interval])) by (grpc_service,grpc_method)",
       "legendFormat": "{{ grpc_service }} | {{grpc_method}}"
      }
     ]
    },
    {
     "title": "Responses (OK)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{service=\"$service\", namespace=\"$NS\", grpc_type=\"unary\", grpc_code=\"OK\"}[$__interval])) by (grpc_service,grpc_method)",
       "legendFormat": "{{ grpc_service }} | {{grpc_method}}"
      }
     ]
    },
    {
     "title": "Responses (not OK)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{service=\"$service\", namespace=\"$NS\", grpc_type=\"unary\", grpc_code!=\"OK\"}[$__interval])) by (grpc_code,grpc_service,grpc_method)",
       "legendFormat": "{{grpc_code }} | {{ grpc_service }} | {{grpc_method}}"
      }
     ]
    },
    {
     "title": "Not handled requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_client_started_total{service=\"$service\", namespace=\"$NS\", grpc_type=\"unary\"}[$__interval])) by (grpc_service, grpc_method) - \nsum(rate(grpc_client_handled_total{service=\"$service\", namespace=\"$NS\", grpc_type=\"unary\"}[$__interval])) by (grpc_service, grpc_method)",
       "legendFormat": "{{ grpc_service }} | {{grpc_method }}"
      }
     ]
    },
    {
     "title": "90%-tile latency of requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, \n  sum(rate(grpc_client_handling_seconds_bucket{service=\"$service\", namespace=\"$NS\"}[$__interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method }}"
      }
     ]
    },
    {
     "title": "99%-tile latency of requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_client_handling_seconds_bucket{service=\"$service\", namespace=\"$NS\"}[$__interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "db_open_connections{namespace=\"$NS\", service=\"$service\"}",
       "legendFormat": "opened | {{ driver }} | {{ kubernetes_pod_name }}"
      },
      {
       "expr": "db_inuse{namespace=\"$NS\", service=\"$service\"}",
       "legendFormat": "used | {{ driver }} | {{ kubernetes_pod_name }}"
      },
      {
       "expr": "db_idle{namespace=\"$NS\", service=\"$service\"}",
       "legendFormat": "idle | {{ driver }} | {{ kubernetes_pod_name }}"
      }
     ]
    },
    {
     "title": "Connections closed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(db_max_idle_closed{namespace=\"$NS\", service=\"$service\"}[$__interval])) by (driver)",
       "legendFormat": "{{ driver }} (SetMaxIdleConns)"
      },
      {
       "expr": "sum(rate(db_max_lifetime_closed{namespace=\"$NS\", service=\"$service\"}[$__interval])) by (driver)",
       "legendFormat": "{{ driver }} (SetConnMaxLifetime)"
      }
     ]
    },
    {
     "title": "Connections wait count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(db_wait_count{namespace=\"$NS\", service=\"$service\"}[$__interval])) by (driver)",
       "legendFormat": "{{ driver }}"
      }
     ]
    },
    {
     "title": "Connections wait time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(db_wait_duration_seconds{namespace=\"$NS\", service=\"$service\"}[$__interval])) by (driver)",
       "legendFormat": "{{ driver }}"
      }
     ]
    }
   ]
  }
 ]
}