{
 "title": "NATS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "NS",
    "label": "namespace",
    "query": {
     "query": "label_values(nats_consumer_duration_count{}, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(nats_consumer_duration_count{namespace=\"$NS\"}, service)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "quantile",
    "query": "\"0.5\",\"0.9\",\"0.99\""
   },
   { "name": "Filters" },
   {
    "name": "stage",
    "query": {
     "query": "label_values(nats_consumer_duration_count{namespace=\"$NS\"}, deployment_environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Services versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(runtime_uptime{namespace=\"$NS\"}[1m])) by ( namespace, service, service_version)"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "repeat": "license",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max_over_time(runtime_uptime{namespace=\"$NS\",deployment_environment=\"$stage\"}[30s])"
    }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time{namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"}[ $__interval])) by(state,service_instance_id)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_runtime_go_goroutines{namespace=\"$NS\", deployment_environment=\"$stage\", service=\"$service\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(process_runtime_go_gc_pause_total_ns{namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"}[$__interval])",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_heap_sys{namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"}) by (service_instance_id)",
     "legendFormat": "virtual address space {{service_instance_id}}"
    },
    {
     "expr": "sum(process_runtime_go_mem_heap_alloc{namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"}) by (service_instance_id)",
     "legendFormat": "allocated heap object  {{service_instance_id}} "
    },
    {
     "expr": "sum(process_runtime_go_mem_heap_inuse{namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"}) by (service_instance_id)",
     "legendFormat": "in-use spans {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_alloc{service=\"$service\", namespace=\"$NS\"}",
     "legendFormat": "bytes allocated | {{service_instance_id}}"
    },
    {
     "expr": "process_runtime_go_mem_heap_inuse{service=\"$service\", namespace=\"$NS\"}",
     "legendFormat": "heap inuse | {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "system_memory_usage{namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"} / 1024 / 1024",
     "legendFormat": "{{state}} {{service_instance_id}}"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "grpc_service" },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(nats_consumer_duration_count{service=\"$service\"}[$__range])) by ( nats_subject) > 0"
    },
    {
     "expr": "sum(increase(nats_consumer_duration_sum{service=\"$service\"}[$__range])) by (nats_subject) \n/ sum(increase(nats_consumer_duration_count{service=\"$service\"}[$__range])) by (nats_subject) > 0"
    },
    {
     "expr": "(sum(increase(nats_consumer_duration_count{nats_code!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\"}[$__range])) by (nats_subject) \n/ sum(increase(nats_consumer_duration_count{service=\"$service\"}[$__range])) by (nats_subject)) >= 0\nor (sum(increase(nats_consumer_duration_count{service=\"$service\"}[$__range])) by (nats_subject) > 0) * 0"
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(increase(nats_consumer_duration_sum{service=\"$service\", namespace=\"$NS\"}[$interval])) by (nats_subject)\n/ sum(increase(nats_consumer_duration_count{service=\"$service\", namespace=\"$NS\"}[$interval])) by (nats_subject)) >= 0",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "stat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nats_consumer_duration_count{service=\"$service\",namespace=\"$NS\"}[$interval]))"
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "stat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(nats_consumer_duration_count{nats_code!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\"}[$__range]))\n/ sum(increase(nats_consumer_duration_count{service=\"$service\"}[$__range])) >= 0)\nor (sum(increase(nats_consumer_duration_count{service=\"$service\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(increase(nats_consumer_duration_sum{service=\"$service\", namespace=\"$NS\"}[$interval])) by (nats_code)\n/ sum(increase(nats_consumer_duration_count{service=\"$service\", namespace=\"$NS\"}[$interval])) by (nats_code)) >= 0",
     "legendFormat": "{{nats_code}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nats_consumer_duration_count{service=\"$service\", namespace=\"$NS\"}[$interval])) by (nats_subject)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Average handling time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(nats_consumer_duration_sum{service=\"$service\", namespace=\"$NS\"}[$interval])) by (nats_subject)",
     "legendFormat": "{{nats_subject}}"
    }
   ]
  },
  {
   "title": "Request error percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nats_consumer_duration_count{service=\"$service\", namespace=\"$NS\", nats_code!~\"^[2-4]..$\"}[$interval])) by (nats_subject)\n/ \nsum(rate(nats_consumer_duration_count{service=\"$service\", namespace=\"$NS\"}[$interval])) by (nats_subject)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "[[quantile]]-quantile latency of requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile,\nsum(rate(nats_consumer_duration_bucket{service=\"$service\", namespace=\"$NS\"}[1m])) by (nats_subject,le)\n)",
     "legendFormat": "{{nats_subject}}"
    }
   ]
  },
  {
   "title": "Request error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_consumer_duration_count{service=\"$service\", namespace=\"$NS\", nats_code!~\"^[2-4]..$\"}[$interval])) by (nats_subject)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate((nats_consumer_response_content_length{}[$interval])))",
     "legendFormat": "response"
    },
    {
     "expr": "sum(irate((nats_consumer_request_content_length{}[$interval])))",
     "legendFormat": "request"
    }
   ]
  }
 ]
}