{
 "title": "OpenTelemetry Collector 0.68.0 v20230112",
 "description": "Provides information about the status of the OpenTelemetry Collector  Contrib ",
 "tags": [
  "opentelemetry",
  "0.68.0"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(otelcol_process_cpu_seconds,namespace)"
    }
   },
   {
    "name": "env",
    "query": {
     "query": "label_values(otelcol_process_cpu_seconds{namespace=~\"$namespace\"},deployment_environment)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(otelcol_process_cpu_seconds{namespace=~\"$namespace\"},job)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Receivers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spans Accepted vs Refused /Second",
   "type": "timeseries",
   "description": "Rate of spans successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{ job=~\"$job\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}} spans accepted / sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{job=~\"$job\"}[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} spans refused /sec"
    }
   ]
  },
  {
   "title": "Metrics Accepted vs Refused Received/Second",
   "type": "timeseries",
   "description": "Rate of metrics successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{ job=~\"$job\"}[$__rate_interval])) by (receiver)",
     "legendFormat": "{{receiver}} accepted /sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points{ job=~\"$job\"}[$__rate_interval])) by (receiver)",
     "legendFormat": "{{ receiver }} refused / sec"
    }
   ]
  },
  {
   "title": "Logs Accepted vs Refused Received/Second",
   "type": "timeseries",
   "description": "Rate of metrics successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_log_records{  job=~\"$job\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}} accepted /sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_log_points{  job=~\"$job\"}[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} refused / sec"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Processor Spans Received, Dropped, Accepted, Refused/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_dropped_spans{job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | dropped"
    },
    {
     "expr": "sum(rate(otelcol_processor_accepted_spans{job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | accepted"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_spans{ job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | refused"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Processor Metric  Dropped, Accepted, Refused/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_dropped_metric_points{job=~\"$job\"}[$__rate_interval])) by (processor)",
     "legendFormat": "{{processor}} | dropped"
    },
    {
     "expr": "sum(rate(otelcol_processor_accepted_metric_points{job=~\"$job\"}[$__rate_interval])) by (processor)",
     "legendFormat": "{{processor}} | accepted"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_metric_points{job=~\"$job\"}[$__rate_interval])) by (processor)",
     "legendFormat": "{{processor}} | refused"
    }
   ]
  },
  {
   "title": "Processor Logs Received, Dropped, Accepted, Refused/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_dropped_log_records{job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | dropped"
    },
    {
     "expr": "sum(rate(otelcol_processor_accepted_log_records{job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | accepted"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_log_records{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | refused"
    }
   ]
  },
  {
   "title": "Batches trigger by size/timeout per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_size_trigger_send{ job=~\"$job\"}[$__interval])) by(processor)",
     "legendFormat": "{{processor}} | size send"
    },
    {
     "expr": "sum(rate(otelcol_processor_batch_timeout_trigger_send{ job=~\"$job\"}[$__interval])) by (processor)",
     "legendFormat": "{{processor}} | timeout send"
    }
   ]
  },
  {
   "title": "Batch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_count{job=~\"$job\"}[$__rate_interval])) by (processor)",
     "legendFormat": "Batch send size count: {{processor}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum{job=~\"$job\"}[$__rate_interval])) by (processor)",
     "legendFormat": "Batch send size sum: {{processor}}"
    }
   ]
  },
  {
   "title": "otelcol_processor_batch_batch_send_size_bucket 95",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(otelcol_processor_batch_batch_send_size_bucket{job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spans Exported vs Failed / Second",
   "type": "timeseries",
   "description": "Rate of spans successfully exported vs Failed per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{job=~\"$job\"}[1m])) by (exporter) >0",
     "legendFormat": "{{exporter}} sent / sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{job=~\"$job\"}[1m])) by (exporter)>0",
     "legendFormat": "{{ exporter }} failed /sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_enqueue_failed_spans{job=~\"$job\"}[1m])) by (exporter)>0",
     "legendFormat": "{{ exporter }}  enqueue failed /sec"
    }
   ]
  },
  {
   "title": "Metrics Exported vs failed /Second",
   "type": "timeseries",
   "description": "Rate of timeseries successfully exported per second",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{ job=~\"$job\"}[$__rate_interval])) by (exporter) > 0",
     "legendFormat": "send | {{exporter}} "
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points{job=~\"$job\"}[$__rate_interval])) by (exporter) >0",
     "legendFormat": "failed | {{ exporter }} "
    },
    {
     "expr": "sum(rate(otelcol_exporter_enqueue_failed_metric_points{ job=~\"$job\"}[$__rate_interval])) by (exporter) >0",
     "legendFormat": "enqueue failed  | {{ exporter }}"
    }
   ]
  },
  {
   "title": "Logs Exported vs failed /Second",
   "type": "timeseries",
   "description": "Rate of timeseries successfully exported per second",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_log_records{job=~\"$job\"}[1m])) by (exporter) >0",
     "legendFormat": "{{exporter}} sent /sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_log_records{job=~\"$job\"}[1m])) by (exporter) >0",
     "legendFormat": "{{ exporter }} failed / sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_enqueue_failed_log_records{job=~\"$job\"}[1m])) by (exporter) >0",
     "legendFormat": "{{ exporter }}  enqueue failed / sec"
    }
   ]
  },
  {
   "title": "Exporter Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(otelcol_exporter_queue_capacity{job=~\"$job\"}) by(exporter)",
     "legendFormat": "cap: {{exporter}}"
    },
    {
     "expr": "max(otelcol_exporter_queue_size{ job=~\"$job\"}) by(exporter)",
     "legendFormat": "size: {{exporter}}"
    }
   ]
  },
  {
   "title": "Failed Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_requests{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Failed request rate: {{exporter}}"
    }
   ]
  },
  {
   "title": "Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(rate(otelcol_process_cpu_seconds{job=~\"$job\"}[$__rate_interval])*100) by (instance)",
     "legendFormat": "Max CPU usage"
    },
    {
     "expr": "avg(rate(otelcol_process_cpu_seconds{job=~\"$job\"}[$__rate_interval])*100) by (instance)",
     "legendFormat": "Avg CPU usage"
    },
    {
     "expr": "min(rate(otelcol_process_cpu_seconds{job=~\"$job\"}[$__rate_interval])*100) by (instance)",
     "legendFormat": "Min CPU usage"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(otelcol_process_memory_rss{job=~\"$job\"})",
     "legendFormat": "Max Memory RSS"
    },
    {
     "expr": "avg(otelcol_process_memory_rss{job=~\"$job\"})",
     "legendFormat": "Avg Memory RSS"
    },
    {
     "expr": "min(otelcol_process_memory_rss{job=~\"$job\"})",
     "legendFormat": "Min Memory RSS"
    }
   ]
  }
 ]
}