{
 "title": "SQL",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "quantile",
    "query": "\"0.5\",\"0.9\",\"0.99\""
   },
   { "name": "Filters" },
   {
    "name": "NS",
    "label": "namespace",
    "query": {
     "query": "label_values(db_sql_client_calls{}, service_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(db_sql_client_calls{service_namespace=\"$NS\"}, service)"
    }
   },
   {
    "name": "stage",
    "query": {
     "query": "label_values(db_sql_client_calls{service_namespace=\"$NS\"}, deployment_environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Services versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(system_cpu_time{service_namespace=\"$NS\"}[1m])) by ( service_namespace, service, service_version)"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "repeat": "license",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max_over_time(runtime_uptime{service_namespace=\"$NS\",deployment_environment=\"$stage\"}[30s])"
    }
   ]
  },
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time{service_namespace=\"$NS\", service=\"$service\",deployment_environment=\"$stage\"}[ $__interval])) by(state,service_instance_id) >= 0",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_runtime_go_goroutines{service_namespace=\"$NS\", deployment_environment=\"$stage\", service_name=\"$service\"} >= 0",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(process_runtime_go_gc_pause_total_ns{service_namespace=\"$NS\", service_name=\"$service\",deployment_environment=\"$stage\"}[$__interval]) >= 0",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_heap_sys{service_namespace=\"$NS\", service_name=\"$service\",deployment_environment=\"$stage\"}) by (service_instance_id) >= 0",
     "legendFormat": "virtual address space {{service_instance_id}}"
    },
    {
     "expr": "sum(process_runtime_go_mem_heap_alloc{service_namespace=\"$NS\", service_name=\"$service\",deployment_environment=\"$stage\"}) by (service_instance_id) >= 0",
     "legendFormat": "allocated heap object  {{service_instance_id}} "
    },
    {
     "expr": "sum(process_runtime_go_mem_heap_inuse{service_namespace=\"$NS\", service_name=\"$service\",deployment_environment=\"$stage\"}) by (service_instance_id) >= 0",
     "legendFormat": "in-use spans {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_alloc{service_name=\"$service\", service_namespace=\"$NS\"} >= 0",
     "legendFormat": "bytes allocated | {{service_instance_id}}"
    },
    {
     "expr": "process_runtime_go_mem_heap_inuse{service_name=\"$service\", service_namespace=\"$NS\"} >= 0 ",
     "legendFormat": "heap inuse | {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "system_memory_usage{service_namespace=\"$NS\", service_name=\"$service\",deployment_environment=\"$stage\"} / 1024 / 1024 >= 0",
     "legendFormat": "{{state}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "SQL requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "grpc_service",
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(db_sql_client_latency_count{service=\"$service\"}[$__range])) by (db_operation) > 0"
    },
    {
     "expr": "sum(increase(db_sql_client_latency_sum{service=\"$service\"}[$__range])) by (db_operation) \n/ sum(increase(db_sql_client_latency_count{service=\"$service\"}[$__range])) by (db_operation) > 0"
    },
    {
     "expr": "(sum(increase(db_sql_client_latency_count{db_sql_status!~\"OK\",service=\"$service\"}[$__range])) by (udb_operationrl) \n/ sum(increase(db_sql_client_latency_count{service=\"$service\"}[$__range])) by (db_operation)) >= 0\nor (sum(increase(db_sql_client_latency_count{service=\"$service\"}[$__range])) by (db_operation) > 0) * 0"
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(increase(db_sql_client_latency_sum{service=\"$service\", service_namespace=\"$NS\"}[$interval])) by ( db_operation)\n/ sum(increase(db_sql_client_latency_count{service=\"$service\", service_namespace=\"$NS\"}[$interval])) by (db_operation)) >= 0",
     "legendFormat": "{{db_operation}}"
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "stat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(db_sql_client_latency_count{service=\"$service\",service_namespace=\"$NS\"}[$interval]))"
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "stat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(db_sql_client_latency_count{db_sql_status!~\"OK\",service=\"$service\"}[$__range]))\n/ sum(increase(db_sql_client_latency_count{service=\"$service\"}[$__range])) >= 0)\nor (sum(increase(db_sql_client_latency_count{service=\"$service\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "SQL status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(increase(db_sql_client_latency_sum{service=\"$service\", service_namespace=\"$NS\"}[$interval])) by (db_sql_status)\n/ sum(increase(db_sql_client_latency_count{service=\"$service\", service_namespace=\"$NS\"}[$interval])) by (db_sql_status)) >= 0",
     "legendFormat": "{{db_sql_status}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(db_sql_client_latency_count{service=\"$service\", service_namespace=\"$NS\"}[$interval])) by (db_operation)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Average handling time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\nincrease(db_sql_client_latency_sum{service=\"$service\", service_namespace=\"$NS\"}[$__rate_interval]) / increase(db_sql_client_latency_count{service=\"$service\", service_namespace=\"$NS\"}[$__rate_interval])\n) by (db_operation) >= 0",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Request error percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(db_sql_client_latency_count{service=\"$service\", service_namespace=\"$NS\", db_sql_status!=\"OK\"}[$interval])) by (db_operation)\n/ \nsum(rate(db_sql_client_latency_count{service=\"$service\", service_namespace=\"$NS\"}[$interval])) by (db_operation)",
     "legendFormat": "{{db_operation}}"
    }
   ]
  },
  {
   "title": "[[quantile]]-quantile latency of requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile,\nsum(rate(db_sql_client_latency_bucket{service=\"$service\", service_namespace=\"$NS\"}[1m])) by ( db_operation,le)\n)",
     "legendFormat": "{{db_operation}}"
    }
   ]
  },
  {
   "title": "Request error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(db_sql_client_latency_count{service=\"$service\", service_namespace=\"$NS\", db_sql_status!=\"OK\"}[$interval])) by (db_operation)",
     "legendFormat": "{{db_operation}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "db_sql_connections_open{service_namespace=\"$NS\", service=\"$service\"} >=0 ",
     "legendFormat": "opened | {{ service_instance_id }}"
    },
    {
     "expr": "db_sql_connections_active{service_namespace=\"$NS\", service=\"$service\"} >=0 ",
     "legendFormat": "used |  | {{ service_instance_id }}"
    },
    {
     "expr": "db_sql_connections_idle{service_namespace=\"$NS\", service=\"$service\"} >=0 ",
     "legendFormat": "idle | | {{ service_instance_id }}"
    }
   ]
  },
  {
   "title": "Connections closed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(db_sql_connections_idle_closed{service_namespace=\"$NS\", service_name=\"$service\"}[$interval])) by (service_instance_id)",
     "legendFormat": "{{ service_instance_id }} (SetMaxIdleConns)"
    },
    {
     "expr": "sum(rate(db_sql_connections_lifetime_closed{service_namespace=\"$NS\", service_name=\"$service\"}[$interval])) by (service_instance_id)",
     "legendFormat": "{{ service_instance_id }} (SetConnMaxLifetime)"
    }
   ]
  },
  {
   "title": "Connections wait count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(db_sql_connections_wait_count{service_namespace=\"$NS\", service_name=\"$service\"}[$interval])) by (service_instance_id)",
     "legendFormat": "{{ service_instance_id }}"
    }
   ]
  },
  {
   "title": "Connections wait time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(db_sql_connections_wait_duration{service_namespace=\"$NS\", service_name=\"$service\"}[$interval])) by ( service_instance_id)",
     "legendFormat": "{{ service_instance_id }}"
    }
   ]
  }
 ]
}