= Changelog

== latest
* example client - rework for more flexible instance view
* move managed infra `docker-compose` to ./docker folder from example
* example came up with new `hotrod`  project port from `jaeger`
* mw: http Wrap w to use our ResponseWriter methods while also exposing  other interfaces that w may implement (http.CloseNotifier,
http.Flusher, http.Hijacker, http.Pusher, io.ReaderFrom) and update gin, echo and chi libs to this fix
* rid of prometheus dependencies, not we all clean
* mw: gin fix status writing
* docker: load loki config + rid from const_labels: const_labels in prometheus, Clients should use own resource for doing that, for example via env: `OTEL_RESOURCE_ATTRIBUTES=license=COM`
* gin: redesign example
* mw: http filter now affect main mw not only httpTrace, appead option WithFilter
* plugin otelsql first version - traces and meterics
* DefaultHistogramBoundaries - allow change explicitly change histogram boundaries
* move modules, plugins to new repo https://github.com/tel-io/instrumentation
* grafana dashboards move to  https://github.com/tel-io/instrumentation/tree/main/grafana-dashboards
* configuration bug fix related to bool values

== v2.0.7
* full function gin mw
* mw: http mux helper
* mw: http option with path exstraction
* mw: http default span naming convention more simple and logical
* mw: grpc stream client/server helper
* not use global meter and trace provider during new instantiation of trace or meter
* documentation related to mw usage
* tel.FromCtx uses global tel instance
* minor improvements and fixes

== v2.0.6
* remove severity fields
* remove redundant duplicate
* new env `DEPLOY_ENVIRONMENT` which expose DeploymentEnvironmentKey semconv
* collector: prometheus  const_labels: stage, namespace replaced with resources,  loki: service_namespace, deployment_environment

== v2.0.5
* grafana feature `tracesToLogs`: ref. from trace => logs
* resources: add `service` which duplicate `ServiceNameKey` from semconv. We can't rid of `ServiceNameKey` because of `tempo` search feature. Furthermore `tracesToLogs` uses  `Loki`  labels which not support dot. That's why we can use simple `service` label and that's why we use for now `service` as label for loki.
* somconv 1,7.0 => 1.10.0
* mw: http extend metrics with `method`, `url`, `status` and `code` fields
* mw: nats add metrics
* grafana/dashboard: nats - full feature reach
* grafana/dashboard: http - redesign
* managed dashboards for `HTTP`
* example: grafana load all managed dashboards
* example: WIP nats service

== v2.0.4
* mw: grpc module move up to OTLP including metrics nad traces
* mw: http move to options
* grafana/dashboard: grpc
* more complex example include

== v2.0.3
* Rid of errors /dev/stderr during closer because of sync - we use OTEL Logger closer for final sync now
* Allow disable OTEL prapagation `OTEL_ENABLE`
* `NewSimple` constructor without OTEL
* Implement options more gracefully OTEL initialization
* Monitor uses options flow for setup and add as composition to Telemetry for `AddHealthChecker` health attach
