= Telemetry.V2 Otel Protocol

Framework which aims to ease logging affair: `Logs`, `Traces` and `Metrics` .

V2 version launch usage of OpenTelemetry specification for all logging directions.
This mean that all logging propagators uses `OTEL` protocol.

Tel use `zap.Logger` as the heart of system.
That why it's pass all zap functions through.

== Motto

Ony context all logs.

Decrease external dependencies as match as possible.

== Logging stack

Logging data exported via `OTEL's` GRPC protocol. `tel` developed to trespass it via https://github.com/open-telemetry/opentelemetry-collector[open-telemetry collector] which should route log data up to any desired log receivers.

Keep in mind that collector has plugin version https://github.com/open-telemetry/opentelemetry-collector-contrib[collector contrib] - this is gateway-adapter to numerous protocols which not yet support `OTEL`, for example grafana loki.

For instance, you can use `opentelemetry-collector-contrib` as `tel` receiver and route logging data to `Grafana Loki`, trace data to `Grafana Tempo` and metric data to `Prometheus + Grafana ;)`

=== Grafana references feature
==== loki to tempo
`tel` approach to put `traceID` field with actual trace ID. All our middlewares should do that or developer should do it by himself

Just call `UpdateTraceFields` before write some logs
[source,go]
----
tel.UpdateTraceFields(ctx)
----

understood grafana should setup `derivedFields` for Loki data source
[source,json]
----
  - name: Loki
    type: loki
    url: http://loki:3100
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          name: trace
          url: '$${__value.raw}'
----

==== tempo to loki
We match `tempo` with `loki` by `service_name` label. All logs should contain traceID by any key form and `service_name`.
In grafana tempo datasource should be configured with `tracesToLogs`
==== prometheus to loki
[source,json]
----
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: true
        mapTagNamesEnabled: false
        tags:
          - service_name
----


== Install

[source,bash]
----
go get github.com/d7561985/tel/v2@latest
----

== Features

* `OTEL` logs implementation

== Env

.OTEL_SERVICE_NAME
service name

`type`: string

.NAMESPACE
project namespace

`type`: string

.DEPLOY_ENVIRONMENT
ENUM: dev, stage, prod

`type`: string

.LOG_LEVEL
info log

.LOG_ENCODE
valid options: `console` and `json` or "none"

none - disable print to console (only OTEL or critical errors)

`type`: string
NOTE:  debug, info, warn, error, dpanic, panic, fatal

.DEBUG
for IsDebug() function

`type`: bool

.SENTRY_DSN
sentry dns

`type`: string

.MONITOR_ENABLE
default: `true`

.MONITOR_ADDR
address where `health`, `prometheus` would be listen

NOTE: address logic represented in net.Listen description

.OTEL_ENABLE
default: `true`

.OTEL_COLLECTOR_GRPC_ADDR
Address to otel collector server via GRPC protocol

.OTEL_EXPORTER_WITH_INSECURE
With insecure ...

.OTEL_RESOURCE_ATTRIBUTES
This optional variable, handled by open-telemetry SDK.
Separator is semicolon.
Put additional resources variables, very suitable!

== Modules, Plugins and ect

Some plugins require external packages, we don'ty like unnecessary increasing dependencies.
Thus offer sub-modules which should be added separately

=== Middlewares

==== http

Already present
[source,go]

----
import(
        "github.com/d7561985/tel/v2/monitoring/metrics"
        mwr "github.com/d7561985/tel/v2/middleware/http"
)
...
	mTracker := metrics.NewHTTPMetric(metrics.DefaultHTTPPathRetriever())
	mw := mwr.NewServer(params.Logger)

    handler := mw.HTTPServerMiddlewareAll(mTracker)
...
----

==== grpc
[source,bash]
----
go get -v github.com/d7561985/tel/middleware/grpc/v2@latest
----

==== NATS

[source,bash]
----
go get -v github.com/d7561985/tel/middleware/natsmw/v2@latest
----

==== chi

[source,bash]
----
go get -v github.com/d7561985/tel/middleware/chi/v2@latest
----

==== echo

[source,bash]
----
go get -v github.com/d7561985/tel/middleware/echo/v2@latest
----

==== Propagators

.github.com/d7561985/tel/v2/propagators/natsprop
Just helper which uses any TextMapPropagator (by default globally declared or via WithPropagators option).
Suitable propagate traces (`propagation.TraceContext`) or baggage(`propagation.Baggage`).

=== Plugins

==== Logging

github.com/d7561985/tel/plugins/pgx/v2

[source,bash]
----
go get -v github.com/d7561985/tel/plugins/pgx/v2@latest
----

== ToDo

* [ ] Expose health check to specific metric
* [ ] Duplicate trace messages for root - ztrace.New just add to chain tree

== Usage

Tale look in `example/demo` folder.
