= Telemetry.V2 Otel Protocol

Framework which aims to ease logging affair: `Logs`, `Traces` and `Metrics`.

V2 version launch usage of OpenTelemetry specification for all logging directions. This mean that all logging propagators uses `OTEL` protocol

Tel use `zap.Logger` as the heart of system. That why it's pass all zap functions through.


== Motto

Ony context all logs.

Decrease external dependencies as match as possible.

== Features
* OTEL trace

== Env

.OTEL_SERVICE_NAME
service name

.PROJECT
obsolete but mean the same as `OTEL_SERVICE_NAME`

`type`: string

.NAMESPACE
project namespace

`type`: string

.LOG_LEVEL
info log

`type`: string
NOTE:  debug, info, warn, error, dpanic, panic, fatal

.DEBUG
for IsDebug() function

`type`: bool

.SENTRY_DSN
sentry dns

`type`: string

.MONITOR_ADDR
address where `health`, `prometheus` would be listen

NOTE: address logic represented in net.Listen description

.OTEL_EXPORTER_OTLP_ENDPOINT
Address to otel collector server via GRPC protocol

.OTEL_RESOURCE_ATTRIBUTES
This optional variable, handled by open-telemetry SDK. Separator is semicolon. Put additional resources variables, very suitable!

== ToDo

* [ ] Expose health check to specific metric

== Usage

Tale look in `example/demo` folder.