= Telemetry.V2 Otel Protocol

Framework which aims to ease logging affair: `Logs`, `Traces` and `Metrics` .

V2 version launch usage of OpenTelemetry specification for all logging directions. This mean that all logging propagators uses `OTEL` protocol.

Tel use `zap.Logger` as the heart of system. That why it's pass all zap functions through.

== Motto
Ony context all logs.

Decrease external dependencies as match as possible.

== Logging stack
Logging data exported via `OTEL's` GRPC protocol. `tel` developed to trespass it via https://github.com/open-telemetry/opentelemetry-collector[open-telemetry collector] which should route log data up to any desired log receivers.

Keep in mind that collector has plugin version https://github.com/open-telemetry/opentelemetry-collector-contrib[collector contrib] - this is gateway-adapter to numerous protocols which not yet  support `OTEL`, for example grafana loki.


For instance,  you can use `opentelemetry-collector-contrib` as `tel` receiver and route logging data to `Grafana Loki`, trace data to `Grafana Tempo` and metric data to `Prometheus + Grafana ;)`

== Features

* `OTEL` logs implementation

== Env

.OTEL_SERVICE_NAME
service name

.PROJECT
obsolete but mean the same as `OTEL_SERVICE_NAME`

`type`: string

.NAMESPACE
project namespace

`type`: string

.LOG_LEVEL
info log

.LOG_ENCODE
valid options: `console` and `json` or "none"

none - disable print to console (only OTEL or critical errors)

`type`: string
NOTE:  debug, info, warn, error, dpanic, panic, fatal

.DEBUG
for IsDebug() function

`type`: bool

.SENTRY_DSN
sentry dns

`type`: string

.MONITOR_ADDR
address where `health`, `prometheus` would be listen

NOTE: address logic represented in net.Listen description

.OTEL_COLLECTOR_GRPC_ADDR
Address to otel collector server via GRPC protocol

.OTEL_EXPORTER_WITH_INSECURE
With insecure ...

.OTEL_RESOURCE_ATTRIBUTES
This optional variable, handled by open-telemetry SDK. Separator is semicolon. Put additional resources variables, very suitable!

== ToDo

* [ ] Expose health check to specific metric

== Usage

Tale look in `example/demo` folder.
