// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package logprocmocks

import (
	context "context"

	logskd "github.com/d7561985/tel/otlplog/logskd"
	mock "github.com/stretchr/testify/mock"
)

// LogProcessor is an autogenerated mock type for the LogProcessor type
type LogProcessor struct {
	mock.Mock
}

// ForceFlush provides a mock function with given fields: ctx
func (_m *LogProcessor) ForceFlush(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Shutdown provides a mock function with given fields: ctx
func (_m *LogProcessor) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Write provides a mock function with given fields: s
func (_m *LogProcessor) Write(s logskd.Log) {
	_m.Called(s)
}
