{
 "title": "HTTP",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "project",
    "query": "label_values(http_request_total{app=~\".+\", kubernetes_namespace=~\"crm\"},app) "
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "le",
    "query": "\"0.005\",\"0.01\",\"0.025\",\"0.05\",\"0.1\",\"0.25\",\"0.5\",\"1\",\"2.5\",\"5\",\"10\",\"+Inf\""
   },
   {
    "name": "quantile",
    "query": "\"0.5\",\"0.9\",\"0.99\""
   },
   { "name": "Filters" },
   { "name": "ns", "label": "namespace", "query": "${VAR_NS}" }
  ]
 },
 "panels": [
  {
   "title": "Services versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_labels{label_app=~\"$project\", label_appver=~\".+\", namespace=~\"$ns\"}[1m])) by (namespace, label_app, label_appver)"
    }
   ]
  },
  {
   "title": "STATUS",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(kube_pod_container_status_ready{container=\"$project\",container!~\"migration|metrics|kafka-topics-check\", namespace=~\"$ns\"}[30s])"
    }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"$ns\", container_name=~\"$project\"}[$interval])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"$project\", kubernetes_namespace=\"$ns\"}",
     "legendFormat": "resident | {{kubernetes_pod_name}}"
    },
    {
     "expr": "process_virtual_memory_bytes{app=\"$project\", kubernetes_namespace=\"$ns\"}",
     "legendFormat": "virtual | {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{app=\"$project\", kubernetes_namespace=\"$ns\"}",
     "legendFormat": "bytes allocated | {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{app=\"$project\", kubernetes_namespace=\"$ns\"}[30s])",
     "legendFormat": "alloc rate | {{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{app=\"$project\", kubernetes_namespace=\"$ns\"}",
     "legendFormat": "stack inuse | {{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{app=\"$project\", kubernetes_namespace=\"$ns\"}",
     "legendFormat": "heap inuse | {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app=\"$project\", kubernetes_namespace=\"$ns\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "OS Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{app=\"$project\", kubernetes_namespace=\"$ns\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{app=\"$project\", kubernetes_namespace=\"$ns\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "HTTP requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "grpc_service" },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(http_request_total{app=\"$project\", kubernetes_namespace=\"$ns\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Global Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(http_request_total{app=\"$project\", kubernetes_namespace=\"$ns\", code=~\"^2..$\"}[$interval])) OR on() vector(0) + \nsum(rate(http_request_total{app=\"$project\", kubernetes_namespace=\"$ns\", code=~\"^3..$\"}[$interval])) OR on() vector(0) + \nsum(rate(http_request_total{app=\"$project\", kubernetes_namespace=\"$ns\", code=~\"^4..$\"}[$interval])) OR on() vector(0))\n/ \nsum(rate(http_request_total{app=\"$project\", kubernetes_namespace=\"$ns\"}[$interval]))"
    }
   ]
  },
  {
   "title": "HTTP code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_total{app=\"$project\", kubernetes_namespace=\"$ns\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_total{app=\"$project\", kubernetes_namespace=\"$ns\"}[$interval])) by (url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Average handling time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_sum{app=\"$project\", kubernetes_namespace=\"$ns\"}[$interval])) by (url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Request error percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_total{app=\"$project\", kubernetes_namespace=\"$ns\", code!~\"^[2-4]..$\"}[$interval])) by (url)\n/ \nsum(rate(http_request_total{app=\"$project\", kubernetes_namespace=\"$ns\"}[$interval])) by (url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "[[quantile]]-quantile latency of requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\nsum(rate(http_request_duration_seconds_histogram_bucket{app=\"$project\", kubernetes_namespace=\"$ns\"}[1m])) by (url,le)\n)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Request error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_total{app=\"$project\", kubernetes_namespace=\"$ns\", code!~\"^[2-4]..$\"}[$interval])) by (url)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "db_open_connections{kubernetes_namespace=\"crm\", app=\"$project\"}",
       "legendFormat": "opened | {{ driver }} | {{ kubernetes_pod_name }}"
      },
      {
       "expr": "db_inuse{kubernetes_namespace=\"crm\", app=\"$project\"}",
       "legendFormat": "used | {{ driver }} | {{ kubernetes_pod_name }}"
      },
      {
       "expr": "db_idle{kubernetes_namespace=\"crm\", app=\"$project\"}",
       "legendFormat": "idle | {{ driver }} | {{ kubernetes_pod_name }}"
      }
     ]
    },
    {
     "title": "Connections closed",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(db_max_idle_closed{kubernetes_namespace=\"crm\", app=\"$project\"}[$interval])) by (driver)",
       "legendFormat": "{{ driver }} (SetMaxIdleConns)"
      },
      {
       "expr": "sum(rate(db_max_lifetime_closed{kubernetes_namespace=\"crm\", app=\"$project\"}[$interval])) by (driver)",
       "legendFormat": "{{ driver }} (SetConnMaxLifetime)"
      }
     ]
    },
    {
     "title": "Connections wait count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(db_wait_count{kubernetes_namespace=\"crm\", app=\"$project\"}[$interval])) by (driver)",
       "legendFormat": "{{ driver }}"
      }
     ]
    },
    {
     "title": "Connections wait time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 64 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(db_wait_duration_seconds{kubernetes_namespace=\"crm\", app=\"$project\"}[$interval])) by (driver)",
       "legendFormat": "{{ driver }}"
      }
     ]
    }
   ]
  }
 ]
}